# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The British Machine Vision Association
brand: The&thinsp;BMVA
email: secretary@bmva.org
description: >- # this means to ignore newlines until "baseurl:"
  The website for the British Machine Vision Association, the UK national
  forum for individuals and organisations involved in research in computer
  vision, image processing and pattern recognition.
baseurl: "/bmva-website" # the subpath of your site, e.g. /blog
url: "https://ndfcampbell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/layout/bmva-logo-tl.png"
twitter_username: TheBMVA
github_username:  BritishMachineVisionAssociation
facebook_username: thebmva

author: Neill Campbell

flickr_user: '131006004@N06'
flickr_api_key: adb4be93419edab991522b4fa92b7029

# Handling Reading
safe: true
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#  - jekyll-liquid


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/multipagethumb.sh
  - assets/thumbnail_script.sh

main_sponsors:
  - name: IAPR
    url: http://www.iapr.org/
    logo: /img/affiliates/logo-iapr.png
sponsors:
  - name: BCS
    url: http://bcs.org.uk/
    logo: /img/affiliates/logo-bcs.png
  - name: IET
    url: http://www.theiet.org/
    logo: /img/affiliates/logo-iet.jpg
  - name: UKIVA
    url: http://www.ukiva.org/
    logo: /img/affiliates/logo-ukiva.jpg
  - name: AVA
    url: http://www.theava.net/
    logo: /img/affiliates/logo-ava.jpg